const DHAMMAPADA = [
  {t:"\"Ý dẫn đầu các pháp,<br>        Ý làm chủ, ý tạo;<br>        Nếu với ý ô nhiễm,<br>        Nói lên hay hành động,<br>        Khổ não bước theo sau,<br>        Như xe, chân vật kéo \"."},
  {t:"\"Ý dẫn đầu các pháp,<br>        Ý làm chủ, ý tạo,<br>        Nếu với ý thanh tịnh,<br>        Nói lên hay hành động,<br>        An lạc bước theo sau,<br>        Như bóng, không rời hình \"."},
  {t:"\"Nó mắng tôi, đánh tôi,<br>        Nó thắng tôi, cướp tôi \"<br>        Ai ôm hiềm hận ấy,<br>        Hận thù không thể nguôi."},
  {t:"\"Nó mắng tôi, đánh tôi,<br>        Nó thắng tôi, cướp tôi, \"<br>        Không ôm hiềm hận ấy,<br>        Hận thù được tự nguôi."},
  {t:"\"Với hận diệt hận thù,<br>        Ðời này không có được.<br>        Không hận diệt hận thù,<br>        Là định luật ngàn thu \"."},
  {t:"\"Người khác không hiểu biết,<br>        Chúng ta đây bị hại.<br>        Chỗ ấy, ai biết được<br>        Tranh luận được lắng êm.\""},
  {t:"\"Ai sống nhìn tịnh tướng,<br>        không hộ trì các căn,<br>        ăn uống thiếu tiết độ,<br>        biếng nhác, chẳng tinh cần.<br>        Ma uy hiếp kẻ ấy,<br>        như cây yếu trước gió \"."},
  {t:"\"Ai sống quán bất tịnh,<br>        Khéo hộ trì các căn,<br>        ăn uống có tiết độ,<br>        có lòng tin, tinh cần,<br>        Ma không uy hiếp được,<br>        Như núi đá, trước gió\""},
  {t:"\"Ai mặc áo cà sa,<br>        tâm chưa rời uế trược,<br>        không tự chế, không thực,<br>        không xứng áo cà sa \"."},
  {t:"\"Ai rời bỏ uế trược,<br>        giới luật khéo nghiêm trì,<br>        tự chế, sống chơn thực,<br>        thật xứng áo cà sa.\""},
  {t:"\"Không chân, tưởng chân thật,<br>        Chân thật, thấy không chân<br>        Họ không đạt chân thật<br>        Do tà tư tà hạnh"},
  {t:"\"Chân thật, biết chân thật,<br>        Không chân, biết không chân.<br>        Chúng đạt được chân thật,<br>        do chánh tư, chánh hạnh.\""},
  {t:"\"Như ngôi nhà vụng lợp,<br>        Mưa liền xâm nhập vào.<br>        Cũng vậy tâm không tu,<br>        Tham dục liền xâm nhập.\""},
  {t:"\"Như ngôi nhà khéo lợp,<br>        Mưa không xâm nhập vào.<br>        Cũng vậy tâm khéo tu,<br>        Tham dục không xâm nhập.\""},
  {t:"\"Nay sầu, đời sau sầu,<br>        Kẻ ác, hai đời sầu;<br>        Nó sầu, nó ưu não,<br>        Thấy nghiệp uế mình làm.\""},
  {t:"\"Nay vui, đời sau vui,<br>        Làm phước, hai đời vui.<br>        Người ấý vui, an vui,<br>        Thấy nghiệp tịnh mình làm.\""},
  {t:"\"Nay than, đời sau than,<br>        Kẻ ác, hai đời than,<br>        than rằng: \"Ta làm ác \"<br>        Ðọa cõi dữ, than hơn.\""},
  {t:"\"Nay sướng, đời sau sướng,<br>        Làm phước, hai đời sướng.<br>        Mừng rằng: \"Ta làm thiện \",<br>        Sanh cõi lành, sướng hơn.\""},
  {t:"\"Nếu người nói nhiều kinh,<br>        Không hành trì, phóng dật;<br>        Như kẻ chăn bò người,<br>        Không phần Sa môn hạnh.\""},
  {t:"\"Dầu nói ít kinh điển,<br>        Nhưng hành pháp, tùy pháp,<br>        Từ bỏ tham, sân, si,<br>        Tỉnh giác, tâm giải thoát,<br>        Không chấp thủ hai đời,<br>        Dự phần Sa môn hạnh.\""},
  {t:"\"Không phóng dật, đường sống,<br>        Phóng dật là đường chết.<br>        Không phóng dật, không chết,<br>        Phóng dật như chết rồi.\""},
  {t:"\"Biết rõ sai biệt ấy,<br>        Người trí không phóng dật,<br>        Hoan hỷ, không phóng dật,<br>        An vui hạnh bậc Thánh.\""},
  {t:"\"Người hằng tu thiền định,<br>        Thường kiên trì tinh tấn.<br>        Bậc trí hưởng Niết Bàn,<br>        Ách an tịnh vô thượng.\""},
  {t:"\"Nỗ lực, giữ chánh niệm,<br>        Tịnh hạnh, hành thận trọng<br>        Tự điều, sống theo pháp,<br>        Ai sống không phóng dật,<br>        Tiếng lành ngày tăng trưởng.\""},
  {t:"\"Nỗ lực, không phóng dật,<br>        Tự điều, khéo chế ngự.<br>        Bậc trí xây hòn đảo,<br>        Nước lụt khó ngập tràn.\""},
  {t:"\"Họ ngu si thiếu trí,<br>        Chuyên sống đời phóng dật.<br>        Người trí, không phóng dật,<br>        Như giữ tài sản quý.\""},
  {t:"\"Chớ sống đời phóng dật,<br>        Chớ mê say dục lạc.<br>        Không phóng dật, thiền định,<br>        Ðạt được an lạc lớn.\""},
  {t:"\"Người trí dẹp phóng dật,<br>        Với hạnh không phóng dật,<br>        Leo lầu cao trí tuệ,<br>        Không sầu, nhìn khổ sầu,<br>        Bậc trí đứng núi cao,<br>        Nhìn kẻ ngu, đất bằng.\""},
  {t:"\"Tinh cần giữa phóng dật,<br>        Tỉnh thức giữa quần mê.<br>        Người trí như ngựa phi,<br>        Bỏ sau con ngựa hèn.\""},
  {t:"\"Ðế Thích không phóng dật,<br>        Ðạt ngôi vị Thiên chủ.<br>        Không phóng dật, được khen;<br>        Phóng dật, thường bị trách.\""},
  {t:"\"Vui thích không phóng dật,<br>        Tỷ kheo sợ phóng dật,<br>        Bước tới như lửa hừng,<br>        Thiêu kiết sử lớn nhỏ.\""},
  {t:"\"Vui thích không phóng dật,<br>        Tỷ kheo sợ phóng dật,<br>        Không thể bị thối đọa,<br>        Nhất định gần Niết Bàn.\""},
  {t:"\"Tâm hoảng hốt giao động,<br>        Khó hộ trì, khó nhiếp,<br>        Người trí làm tâm thẳng,<br>        Như thợ tên, làm tên.\""},
  {t:"\"Như cá quăng trên bờ,<br>        Vất ra ngoài thủy giới;<br>        Tâm này vũng vẫy mạnh,<br>        Hãy đoạn thế lực Ma.\""},
  {t:"\"Khó nắm giữ, khinh động,<br>        Theo các dục quay cuồng.<br>        Lành thay, điều phục tâm;<br>        Tâm điều, an lạc đến.\""},
  {t:"\"Tâm khó thấy, tế nhị,<br>        Theo các dục quay cuồng.<br>        Người trí phòng hộ tâm,<br>        Tâm hộ, an lạc đến.\""},
  {t:"\"Chạy xa, sống một mình,<br>        Không thân, ẩn hang sâu<br>        Ai điều phục được tâm,<br>        Thoát khỏi Ma trói buộc\""},
  {t:"\"Ai tâm không an trú,<br>        Không biết chân diệu pháp,<br>        Tịnh tín bị rúng động,<br>        Trí tuệ không viên thành.\""},
  {t:"\"Tâm không đầy tràn dục,<br>        Tâm không (hận) công phá,<br>        Ðoạn tuyệt mọi thiện ác,<br>        Kẻ tỉnh không sợ hãi,\""},
  {t:"\"Biết thân như đồ gốm,<br>        Trú tâm như thành trì,<br>        Chống ma với gươm trí;<br>        Giữ chiến thắng không tham\""},
  {t:"\"Không bao lâu thân này,<br>        Sẽ nằm dài trên đất,<br>        Bị vất bỏ, vô thức,<br>        Như khúc cây vô dụng.\""},
  {t:"\"Kẻ thù hại kẻ thù,<br>        Oan gia hại oan gia,<br>        Không bằng tâm hướng tà,<br>        Gây ác cho tự thân.\""},
  {t:"\"Ðiều mẹ cha bà con,<br>        Không có thể làm được<br>        Tâm hướng chánh làm được<br>        Làm được tốt đẹp hơn.\""},
  {t:"\"Ai chinh phục đất này<br>        Dạ ma, Thiên giới này?<br>        Ai khéo giảng Pháp cú,<br>        Như người khéo hái hoa?\""},
  {t:"\"Hữu học chinh phục đất,<br>        Dạ ma, Thiên giới này.<br>        Hữu học giảng Pháp cú,<br>        Như người khéo hái hoa.\""},
  {t:"\"Biết thân như bọt nước,<br>        Ngộ thân là như huyễn,<br>        Bẻ tên hoa của ma,<br>        Vượt tầm mắt thần chết.\""},
  {t:"\"Người nhặt các loại hoa,<br>        Ý đắm say, tham nhiễm,<br>        Bị thần chết mang đi,<br>        Như lụt trôi làng ngủ.\""},
  {t:"\"Người nhặt các loại hoa,<br>        Ý đắm say tham nhiễm,<br>        Các dục chưa thỏa mãn,<br>        Ðã bị chết chinh phục.\""},
  {t:"\"Như ong đến với hoa,<br>        Không hại sắc và hương,<br>        Che chở hoa, lấy nhụy.<br>        Bậc Thánh đi vào làng \"."},
  {t:"\"Không nên nhìn lỗi người,<br>        Người làm hay không làm.<br>        Nên nhìn tự chính mình.<br>        Có làm hay không làm.\""},
  {t:"\"Như bông hoa tươi đẹp,<br>        Có sắc nhưng không hương.<br>        Cũng vậy, lời khéo nói,<br>        Không làm, không kết quả.\""},
  {t:"\"Như bông hoa tươi đẹp,<br>        Có sắc lại thêm hương;<br>        Cũng vậy, lời khéo nói,<br>        Có làm, có kết quả.\""},
  {t:"\"Như từ một đống hoa,<br>        Nhiều tràng hoa được làm.<br>        Cũng vậy, thân sanh tử,<br>        Phải làm nhiều việc lành.\""},
  {t:"\"Hương các loại hoa thơm<br>        Không ngược bay chiều gió<br>        Nhưng hương người đức hạnh<br>        Ngược gió khắp tung bay<br>        Chỉ có bậc chân nhân<br>        Tỏa khắp mọi phương trời.\""},
  {t:"\"Hoa chiên đàn, già la,<br>        Hoa sen, hoa vũ quý,<br>        Giữa những hương hoa ấy,<br>        Giới hương là vô thượng.\""},
  {t:"\"Ít giá trị hương này,<br>        Hương già la, chiên đàn;<br>        Chỉ hương người đức hạnh,<br>        Tối thượng tỏa Thiên giới.\""},
  {t:"\"Nhưng ai có giới hạnh,<br>        An trú không phóng dật,<br>        Chánh trí, chơn giải thoát,<br>        Ác ma không thấy đường.\""},
  {t:"\"Như giữa đống rác nhớp,<br>        Quăng bỏ trên đường lớn,<br>        Chỗ ấy hoa sen nở,<br>        Thơm sạch, đẹp ý người.\""},
  {t:"\"Cũng vậy giữa quần sanh,<br>        Uế nhiễm, mù, phàm tục,<br>        Ðệ tử bậc Chánh Giác,<br>        Sáng ngời với Tuệ Trí.\""},
  {t:"\"Ðêm dài cho kẻ thức,<br>        Ðường dài cho kẻ mệt,<br>        Luân hồi dài, kẻ ngu,<br>        Không biết chơn diệu pháp.\""},
  {t:"\"Tìm không được bạn đường,<br>        Hơn mình hay bằng mình,<br>        Thà quyết sống một mình,<br>        Không bè bạn kẻ ngu.\""},
  {t:"\"Con tôi, tài sản tôi,<br>        Người ngu sanh ưu não,<br>        Tự ta, ta không có,<br>        Con đâu, tài sản đâu.\""},
  {t:"\"Người ngu nghĩ mình ngu,<br>        Nhờ vậy thành có trí.<br>        Người ngu tưởng có trí,<br>        Thật xứng gọi chí ngu.\""},
  {t:"\"Người ngu, dầu trọn đời,<br>        Thân cận người có trí,<br>        Không biết được Chánh pháp,<br>        Như muỗng với vị canh.\""},
  {t:"\"Người trí, dầu một khắc,<br>        Thân cận người có trí,<br>        Biết ngay chân diệu pháp,<br>        Như lưỡi với vị canh.\""},
  {t:"\"Người ngu si thiếu trí,<br>        Tự ngã thành kẻ thù.<br>        Làm các nghiệp không thiện,<br>        Phải chịu quả đắng cay.\""},
  {t:"\"Nghiệp làm không chánh thiện,<br>        Làm rồi sanh ăn năn,<br>        Mặt nhuốm lệ, khóc than,<br>        Lãnh chịu quả dị thục.\""},
  {t:"\"Và nghiệp làm chánh thiện,<br>        Làm rồi không ăn năn,<br>        Hoan hỷ, ý đẹp lòng,<br>        Hưởng thọ quả dị thục.\""},
  {t:"\"Người ngu nghĩ là ngọt,<br>        Khi ác chưa chín muồi;<br>        Ác nghiệp chín muồi rồi,<br>        Người ngu chịu khổ đau.\""},
  {t:"\"Tháng tháng với ngọn cỏ,<br>        Người ngu có ăn uống<br>        Không bằng phần mười sáu<br>        Người hiểu pháp hữu vi.\""},
  {t:"\"Nghiệp ác đã được làm,<br>        Như sữa, không đông ngay,<br>        Cháy ngầm theo kẻ ngu,<br>        Như lửa tro che đậy.\""},
  {t:"\"Tự nó chịu bất hạnh,<br>        Khi danh đến kẻ ngu.<br>        Vận may bị tổn hại,<br>        Ðầu nó bị nát tan.\""},
  {t:"\"Ưa danh không tương xứng,<br>        Muốn ngồi trước tỷ kheo,<br>        Ưa quyền tại tịnh xá,<br>        Muốn mọi người lễ kính.\""},
  {t:"\"Mong cả hai tăng, tục,<br>        Nghĩ rằng (chính ta làm).<br>        Trong mọi việc lớn nhỏ,<br>        Phải theo mệnh lệnh ta \"<br>        Người ngu nghĩ như vậy<br>        Dục và mạn tăng trưởng."},
  {t:"\"Khác thay duyên thế lợi,<br>        Khác thay đường Niết Bàn.<br>        Tỷ kheo, đệ tử Phật,<br>        Hãy như vậy thắng tri.<br>        Chớ ưa thích cung kính,<br>        Hãy tu hạnh viễn ly.\""},
  {t:"\"Nếu thấy bậc hiền trí,<br>        Chỉ lỗi và khiển trách,<br>        Như chỉ chỗ chôn vàng<br>        Hãy thân cận người trí!<br>        Thân cận người như vậy,<br>        Chỉ tốt hơn, không xấu.\""},
  {t:"\"Những người hay khuyên dạy,<br>        Ngăn người khác làm ác,<br>        Ðược người hiền kính yêu,<br>        Bị người ác không thích.\""},
  {t:"\"Chớ thân với bạn ác,<br>        Chớ thân kẻ tiểu nhân.<br>        Hãy thân người bạn lành,<br>        Hãy thân bậc thượng nhân.\""},
  {t:"\"Pháp hỷ đem an lạc,<br>        Với tâm tư thuần tịnh;<br>        Người trí thường hoan hỷ,<br>        Với pháp bậc Thánh thuyết.\""},
  {t:"\"Người trị thủy dẫn nước,<br>        Kẻ làm tên nắn tên,<br>        Người thợ mộc uốn gỗ,<br>        Bậc trí nhiếp tự thân.\""},
  {t:"\"Như đá tảng kiên cố,<br>        Không gió nào giao động,<br>        Cũng vậy, giữa khen chê,<br>        Người trí không giao động.\""},
  {t:"\"Như hồ nước sâu thẳm,<br>        Trong sáng, không khuấy đục,<br>        Cũng vậy, nghe chánh pháp,<br>        Người trí hưởng tịnh lạc.\""},
  {t:"\"Người hiền bỏ tất cả,<br>        Người lành không bàn dục,<br>        Dầu cảm thọ lạc khổ,<br>        Bậc trí không vui buồn.\""},
  {t:"\"Không vì mình, vì người.<br>        Không cầu được con cái,<br>        Không tài sản quốc độ,<br>        Không cầu mình thành tựu,<br>        Với việc làm phi pháp.<br>        Vị ấy thật trì giới,<br>        Có trí tuệ, đúng pháp.\""},
  {t:"\"Ít người giữa nhân loại,<br>        Ðến được bờ bên kia<br>        Còn số người còn lại,<br>        Xuôi ngược chạy bờ này.\""},
  {t:"\"Những ai hành trì pháp,<br>        Theo chánh pháp khéo dạy,<br>        Sẽ đến bờ bên kia,<br>        Vượt ma lực khó thoát.\""},
  {t:"\"Kẻ trí bỏ pháp đen,<br>        Tu tập theo pháp trắng.<br>        Bỏ nhà, sống không nhà,<br>        Sống viễn ly khổ lạc.\""},
  {t:"\"Hãy cầu vui Niết Bàn,<br>        Bỏ dục, không sở hữu,<br>        Kẻ trí tự rửa sạch,<br>        Cấu uế từ nội tâm.\""},
  {t:"\"Những ai với chánh tâm,<br>        Khéo tu tập giác chi,<br>        Từ bỏ mọi ái nhiễm,<br>        Hoan hỷ không chấp thủ.<br>        Không lậu hoặc, sáng chói,<br>        Sống tịch tịnh ở đời.\""},
  {t:"\"Ðích đã đến, không sầu,<br>        Giải thoát ngoài tất cả,<br>        Ðoạn trừ mọi buộc ràng,<br>        Vị ấy không nhiệt não.\""},
  {t:"\"Tự sách tấn, chánh niệm,<br>        Không thích cư xá nào,<br>        Như ngỗng trời rời ao,<br>        Bỏ sau mọi trú ẩn.\""},
  {t:"\"Tài sản không chất chứa,<br>        Ăn uống biết liễu tri,<br>        Tự tại trong hành xứ,<br>        \"Không vô tướng, giải thoát, \"<br>        Như chim giữa hư không,<br>        Hướng chúng đi khó tìm.\""},
  {t:"\"Ai lậu hoặc đoạn sạch,<br>        Ăn uống không tham đắm,<br>        Tự tại trong hành xứ,<br>        \"Không, vô tướng giải thoát. \"<br>        Như chim giữa hư không,<br>        Dấu chân thật khó tìm. \""},
  {t:"\"Ai nhiếp phục các căn,<br>        Như đánh xe điều ngự,<br>        Mạn trừ, lậu hoặc dứt,<br>        Người vậy, Chư Thiên mến.\""},
  {t:"\"Như đất, không hiềm hận,<br>        Như cột trụ, kiên trì,<br>        Như hồ, không bùn nhơ,<br>        Không luân hồi, vị ấy.\""},
  {t:"\"Người tâm ý an tịnh,<br>        Lời an, nghiệp cũng an,<br>        Chánh trí, chơn giải thoát,<br>        Tịnh lạc là vị ấy.\""},
  {t:"\"Không tin, hiểu vô vi.<br>        Người cắt mọi hệ lụy<br>        Cơ hội tận, xả ly<br>        Vị ấy thật tối thượng.\""},
  {t:"\"Làng mạc hay rừng núi<br>        Thung lũng hay đồi cao,<br>        La Hán trú chỗ nào,<br>        Ðất ấy thật khả ái \"."},
  {t:"\"Khả ái thay núi rừng,<br>        Chỗ người phàm không ưa,<br>        Vị ly tham ưa thích,<br>        Vì không tìm dục lạc.\""},
  {t:"\"Dầu nói ngàn ngàn lời,<br>        Nhưng không gì lợi ích,<br>        Tốt hơn một câu nghĩa,<br>        Nghe xong, được tịnh lạc.\""},
  {t:"\"Dầu nói ngàn câu kệ<br>        Nhưng không gì lợi ích,<br>        Tốt hơn nói một câu,<br>        Nghe xong, được tịnh lạc.\""},
  {t:"\"Dầu nói trăm câu kệ<br>        Nhưng không gì lợi ích,<br>        Tốt hơn một câu pháp,<br>        Nghe xong, được tịnh lạc.\""},
  {t:"\"Dầu tại bãi chiến trường<br>        Thắng ngàn ngàn quân địch,<br>        Tự thắng mình tốt hơn,<br>        Thật chiến thắng tối thượng.\""},
  {t:"\"Tự thắng, tốt đẹp hơn,<br>        Hơn chiến thắng người khác.<br>        Người khéo điều phục mình,<br>        Thường sống tự chế ngự.\""},
  {t:"\"Dầu Thiên Thần, Thát Bà,<br>        Dầu Ma vương, Phạm Thiên<br>        Không ai chiến thắng nổi,<br>        Người tự thắng như vậy.\""},
  {t:"\"Tháng tháng bỏ ngàn vàng,<br>        Tế tự cả trăm năm,<br>        Chẳng bằng trong giây lát,<br>        Cúng dường bậc tự tu.<br>        Cùng dường vậy tốt hơn,<br>        Hơn trăm năm tế tự.\""},
  {t:"\"Dầu trải một trăm năm,<br>        Thờ lửa tại rừng sâu,<br>        Chẳng bằng trong giây lát,<br>        Cúng dường bậc tự tu.<br>        Cúng dường vậy tốt hơn,<br>        Hơn trăm năm tế tự.\""},
  {t:"\"Suốt năm cúng tế vật,<br>        Ðể cầu phước ở đời.<br>        Không bằng một phần tư<br>        Kính lễ bậc chánh trực.\""},
  {t:"\"Thường tôn trọng, kính lễ<br>        Bậc kỳ lão trưởng thượng,<br>        Bốn pháp được tăng trưởng:<br>        Thọ, sắc, lạc, sức mạnh.\""},
  {t:"\"Dầu sống một trăm năm<br>        Ác giới, không thiền định,<br>        Tốt hơn sống một ngày,<br>        Trì giới, tu thiền định.\""},
  {t:"\"Ai sống một trăm năm,<br>        Ác tuệ, không thiền định.<br>        Tốt hơn sống một ngày,<br>        Có tuệ, tu thiền định.\""},
  {t:"\"Ai sống một trăm năm,<br>        Lười nhác không tinh tấn,<br>        Tốt hơn sống một ngày<br>        Tinh tấn tận sức mình.\""},
  {t:"\"Ai sống một trăm năm,<br>        Không thấy pháp sinh diệt,<br>        Tốt hơn sống một ngày,<br>        Thấy được pháp sinh diệt.\""},
  {t:"\"Ai sống một trăm năm,<br>        Không thấy câu bất tử,<br>        Tốt hơn sống một ngày,<br>        Thấy được câu bất tử.\""},
  {t:"\"Ai sống một trăm năm,<br>        Không thấy pháp tối thượng,<br>        Tốt hơn sống một ngày,<br>        Thấy được pháp tối thượng.\""},
  {t:"\"Hãy gấp làm điều lành,<br>        Ngăn tâm làm điều ác.<br>        Ai chậm làm việc lành,<br>        Ý ưa thích việc ác.\""},
  {t:"\"Nếu người làm điều ác,<br>        Chớ tiếp tục làm thêm.<br>        Chớ ước muốn điều ác,<br>        Chứa ác, tất chịu khổ.\""},
  {t:"\"Nếu người làm điều thiện,<br>        Nên tiếp tục làm thêm.<br>        Hãy ước muốn điều thiện,<br>        Chứa thiện, được an lạc.\""},
  {t:"\"Người ác thấy là hiền.<br>        Khi ác chưa chín muồi,<br>        Khi ác nghiệp chín muồi,<br>        Người ác mới thấy ác.\""},
  {t:"\"Người hiền thấy là ác,<br>        Khi thiện chưa chín muồi.<br>        Khi thiện được chín muồi,<br>        Người hiền thấy là thiện.\""},
  {t:"\"Chớ chê khinh điều ác,<br>        Cho rằng \"chưa đến mình \",<br>        Như nước nhỏ từng giọt,<br>        Rồi bình cũng đầy tràn.<br>        Người ngu chứa đầy ác<br>        Do chất chứa dần dần.\""},
  {t:"\"Chớ chê khinh điều thiện<br>        Cho rằng \"Chưa đến mình, \"<br>        Như nước nhỏ từng giọt,<br>        Rồi bình cũng đầy tràn.<br>        Người trí chứa đầy thiện,<br>        Do chất chứa dần dần.\""},
  {t:"\"Ít bạn đường, nhiều tiền,<br>        Người buôn tránh đường hiểm.<br>        Muốn sống, tránh thuốc độc,<br>        Hãy tránh ác như vậy.\""},
  {t:"\"Bàn tay không thương tích,<br>        Có thể cầm thuốc độc.<br>        Không thương tích, tránh độc,<br>        Không làm, không có ác.\""},
  {t:"\"Hại người không ác tâm,<br>        Người thanh tịnh, không uế,<br>        Tội ác đến kẻ ngu,<br>        Như ngược gió tung bụi.\""},
  {t:"\"Một số sinh bào thai,<br>        Kẻ ác sinh địa ngục,<br>        Người thiện lên cõi trời,<br>        Vô lậu chứng Niết Bàn.\""},
  {t:"\"Không trên trời, giữa biển,<br>        Không lánh vào động núi,<br>        Không chỗ nào trên đời,<br>        Trốn được quả ác nghiệp.\""},
  {t:"\"Không trên trời, giữa biển,<br>        Không lánh vào động núi,<br>        Không chỗ nào trên đời,<br>        Trốn khỏi tay thần chết.\""},
  {t:"\"Mọi người sợ hình phạt,<br>        Mọi người sợ tử vong.<br>        Lấy mình làm ví dụ<br>        Không giết, không bảo giết.\""},
  {t:"\"Mọi người sợ hình phạt,<br>        Mọi người thích sống còn;<br>        Lấy mình làm ví dụ,<br>        Không giết, không bảo giết.\""},
  {t:"\"Chúng sanh cầu an lạc,<br>        Ai dùng trượng hại người,<br>        Ðể tìm lạc cho mình,<br>        Ðời sau không được lạc.\""},
  {t:"\"Chúng sanh cầu an lạc,<br>        Không dùng trượng hại người,<br>        Ðể tìm lạc cho mình,<br>        Ðời sau được hưởng lạc.\""},
  {t:"\"Chớ nói lời ác độc,<br>        Nói ác, bị nói lại,<br>        Khổ thay lời phẫn nộ,<br>        Ðao trượng phản chạm mình.\""},
  {t:"\"Nếu tự mình yên lặng,<br>        Như chiếc chuông bị bể.<br>        Ngươi đã chứng Niết Bàn<br>        Ngươi không còn phẫn nộ.\""},
  {t:"\"Với gậy người chăn bò,<br>        Lùa bò ra bãi cỏ;<br>        Cũng vậy, già và chết,<br>        Lùa người đến mạng chung.\""},
  {t:"\"Người ngu làm điều ác,<br>        Không ý thức việc làm.<br>        Do tự nghiệp, người ngu<br>        Bị nung nấu, như lửa.\""},
  {t:"\"Dùng trượng phạt không trượng,<br>        Làm ác người không ác.<br>        Trong mười loại khổ đau,<br>        Chịu gấp một loại khổ.\""},
  {t:"\"Hoặc khổ thọ khốc liệt,<br>        Thân thể bị thương vong,<br>        Hoặc thọ bệnh kịch liệt,<br>        Hay loạn ý tán tâm.\""},
  {t:"\"Hoặc tai họa từ vua,<br>        Hay bị vu trọng tội;<br>        Bà con phải ly tán,<br>        Tài sản bị nát tan.\""},
  {t:"\"Hoặc phòng ốc nhà cửa<br>        Bị hỏa tai thiêu đốt.<br>        Khi thân hoại mạng chung,<br>        Ác tuệ sanh địa ngục.\""},
  {t:"\"Không phải sống lõa thể<br>        Bện tóc, tro trét mình,<br>        Tuyệt thực, lăn trên đất,<br>        Sống nhớp, siêng ngồi xổm,<br>        Làm con người được sạch,<br>        Nếu không trừ nghi hoặc.\""},
  {t:"\"Ai sống tự trang sức,<br>        Nhưng an tịnh, nhiếp phục,<br>        Sống kiên trì, phạm hạnh,<br>        Không hại mọi sinh linh,<br>        Vị ấy là phạm chí,<br>        Hay sa môn, khất sĩ.\""},
  {t:"\"Thật khó tìm ở đời,<br>        Người biết thẹn, tự chế,<br>        Biết tránh né chỉ trích<br>        Như ngựa hiền tránh roi.\""},
  {t:"\"Như ngựa hiền chạm roi,<br>        Hãy nhiệt tâm, hăng hái,<br>        Với tín, giới, tinh tấn,<br>        Thiền định cùng trạch pháp.<br>        Minh hạnh đủ, chánh niệm,<br>        Ðoạn khổ này vô lượng.\""},
  {t:"\"Người trị thủy dẫn nước,<br>        Kẻ làm tên nắn tên,<br>        Người thợ mộc uốn ván,<br>        Bậc tự điều, điều thân.\""},
  {t:"\"Cười gì, hân hoan gì,<br>        Khi đời mãi bị thiêu?<br>        Bị tối tăm bao trùm,<br>        Sao không tìm ngọn đèn?\""},
  {t:"\"Hãy xem bong bóng đẹp,<br>        Chỗ chất chứa vết thương,<br>        Bệnh hoạn nhiều suy tư,<br>        Thật không gì trường cửu.\""},
  {t:"\"Sắc này bị suy già,<br>        Ổ tật bệnh, mỏng manh,<br>        Nhóm bất tịnh, đỗ vỡ,<br>        Chết chấm dứt mạng sống.\""},
  {t:"\"Như trái bầu mùa thu,<br>        Bị vất bỏ quăng đi,<br>        Nhóm xương trắng bồ câu,<br>        Thấy chúng còn vui gì?\""},
  {t:"\"Thành này làm bằng xương,<br>        Quét tô bằng thịt máu,<br>        Ở đây già và chết,<br>        Mạn, lừa đảo chất chứa.\""},
  {t:"\"Xe vua đẹp cũng già.<br>        Thân này rồi sẽ già,<br>        Pháp bậc thiện, không già.<br>        Như vậy bậc chí thiện<br>        Nói lên cho bậc thiện.\""},
  {t:"\"Người ít nghe kém học,<br>        Lớn già như trâu đực.<br>        Thịt nó tuy lớn lên,<br>        Nhưng tuệ không tăng trưởng.\""},
  {t:"\"Lang thang bao kiếp sống<br>        Ta tìm nhưng chẳng gặp,<br>        Người xây dựng nhà này,<br>        Khổ thay, phải tái sanh.\""},
  {t:"\"Ôi! Người làm nhà kia<br>        Nay ta đã thấy ngươi!<br>        Ngươi không làm nhà nữa.<br>        Ðòn tay ngươi bị gẫy,<br>        Kèo cột ngươi bị tan<br>        Tâm ta đạt tịch diệt,<br>        Tham ái thảy tiêu vong.\""},
  {t:"\"Lúc trẻ, không phạm hạnh,<br>        Không tìm kiếm bạc tiền.<br>        Như cò già bên ao,<br>        Ủ rũ, không tôm cá.\""},
  {t:"\"Lúc trẻ không phạm hạnh,<br>        Không tìm kiếm bạc tiền;<br>        Như cây cung bị gẫy,<br>        Thở than những ngày qua.\""},
  {t:"\"Nếu biết yêu tự ngã,<br>        Phải khéo bảo vệ mình,<br>        Người trí trong ba canh,<br>        Phải luôn luôn tỉnh thức.\""},
  {t:"\"Trước hết tự đặt mình,<br>        Vào những gì thích đáng.<br>        Sau mới giáo hóa người,<br>        Người trí khỏi bị nhiễm.\""},
  {t:"\"Hãy tự làm cho mình,<br>        Như điều mình dạy người.<br>        Khéo tự điều, điều người,<br>        Khó thay, tự điều phục!\""},
  {t:"\"Tự mình y chỉ mình,<br>        Nào có y chỉ khác.<br>        Nhờ khéo điều phục mình,<br>        Ðược y chỉ khó được.\""},
  {t:"\"Ðiều ác tự mình làm,<br>        Tự mình sanh, mình tạo.<br>        Nghiền nát kẻ ngu si,<br>        Như kim cương, ngọc báu.\""},
  {t:"\"Phá giới quá trầm trọng,<br>        Như dây leo bám cây<br>        Gieo hại cho tự thân,<br>        Như kẻ thù mong ước.\""},
  {t:"\"Dễ làm các điều ác,<br>        Dễ làm tự hại mình.<br>        Còn việc lành, việc tốt,<br>        Thật tối thượng khó làm.\""},
  {t:"\"Kẻ ngu si miệt thị,<br>        Giáo pháp bậc La Hán,<br>        Bậc Thánh, bậc chánh mạng.<br>        Chính do ác kiến này,<br>        Như quả loại cây lau<br>        Mang quả tự hoại diệt.\""},
  {t:"\"Tự mình, làm điều ác,<br>        Tự mình làm nhiễm ô,<br>        Tự mình không làm ác,<br>        Tự mình làm thanh tịnh.<br>        Tịnh, không tịnh tự mình,<br>        Không ai thanh tịnh ai!\""},
  {t:"\"Chớ theo pháp hạ liệt.<br>        Chớ sống mặc, buông lung;<br>        Chớ tin theo tà kiến,<br>        Chớ tăng trưởng tục trần.\""},
  {t:"\"Dầu lợi người bao nhiêu,<br>        Chớ quên phần tư lợi,<br>        Nhờ thắng trí tư lợi.<br>        Hãy chuyên tâm lợi mình.\""},
  {t:"\"Nỗ lực, chớ phóng dật!<br>        Hãy sống theo chánh hạnh;<br>        Người chánh hạnh hưởng lạc,<br>        Cả đời này, đời sau.\""},
  {t:"\"Hãy khéo sống chánh hạnh,<br>        Chớ sống theo tà hạnh!<br>        Người chánh hạnh hưởng lạc,<br>        Cả đời này, đời sau.\""},
  {t:"\"Hãy nhìn như bọt nước,<br>        Hãy nhìn như cảnh huyễn!<br>        Quán nhìn đời như vậy,<br>        Thần chết không bắt gặp.\""},
  {t:"\"Hãy đến nhìn đời này,<br>        Như xe vua lộng lẫy,<br>        Người ngu mới tham đắm,<br>        Kẻ trí nào đắm say.\""},
  {t:"\"Ai sống trước buông lung,<br>        Sau sống không phóng dật,<br>        Chói sáng rực đời này.<br>        Như trăng thoát mây che.\""},
  {t:"\"Ai dùng các hạnh lành,<br>        Làm xóa mờ nghiệp ác,<br>        Chói sáng rực đời này,<br>        Như trăng thoát mây che.\""},
  {t:"\"Ðời này thật mù quáng,<br>        Ít kẻ thấy rõ ràng.<br>        Như chim thoát khỏi lưới,<br>        Rất ít đi thiên giới.\""},
  {t:"\"Như chim thiên nga bay,<br>        Thần thông liệng giữa trời;<br>        Chiến thắng ma, ma quân,<br>        Kẻ trí thoát đời này.\""},
  {t:"\"Ai vi phạm một pháp,<br>        Ai nói lời vọng ngữ,<br>        Ai bác bỏ đời sau,<br>        Không ác nào không làm.\""},
  {t:"\"Keo kiết không sanh thiên,<br>        Kẻ ngu ghét bố thí,<br>        Người trí thích bố thí,<br>        Ðời sau, được hưởng lạc.\""},
  {t:"\"Hơn thống lãnh cõi đất,<br>        Hơn được sanh cõi trời,<br>        Hơn chủ trì vũ trụ,<br>        Quả Dự Lưu tối thắng.\""},
  {t:"\"Vị chiến thắng không bại,<br>        Vị bước đi trên đời,<br>        Không dấu tích chiến thắng,<br>        Phật giới rộng mênh mông,<br>        Ai dùng chân theo dõi<br>        Bậc không để dấu tích?\""},
  {t:"\"Ai giải tỏa lưới tham,<br>        Ái phược hết dắt dẫn,<br>        Phật giới rộng mênh mông,<br>        Ai dùng chân theo dõi,<br>        Bậc không để dấu tích?\""},
  {t:"\"Người trí chuyên thiền định,<br>        Thích an tịnh viễn ly,<br>        Chư thiên đều ái kính,<br>        Bậc chánh giác, chánh niệm.\""},
  {t:"\"Khó thay, được làm người,<br>        Khó thay, được sống còn,<br>        Khó thay, nghe diệu pháp,<br>        Khó thay, Phật ra đời!\""},
  {t:"\"Không làm mọi điều ác.<br>        Thành tựu các hạnh lành,<br>        Tâm ý giữ trong sạch,<br>        Chính lời chư Phật dạy.\""},
  {t:"\"Chư Phật thường giảng dạy;<br>        Nhẫn, khổ hạnh tối thượng,<br>        Niết bàn, quả tối thượng;<br>        Xuất gia không phá người;<br>        Sa môn không hại người.\""},
  {t:"\"Không phỉ báng, phá hoại,<br>        Hộ trì giới căn bản,<br>        Ăn uống có tiết độ,<br>        Sàng tọa chỗ nhàn tịnh<br>        Chuyên chú tăng thượng tâm,<br>        Chính lời chư Phật dạy.\""},
  {t:"\"Dầu mưa bằng tiền vàng,<br>        Các dục khó thỏa mãn.<br>        Dục đắng nhiều ngọt ít,<br>        Biết vậy là bậc trí.\""},
  {t:"\"Ðệ tử bậc chánh giác,<br>        Không tìm cầu dục lạc,<br>        Dầu là dục chư thiên,<br>        Chỉ ưa thích ái diệt.\""},
  {t:"\"Loài người sợ hoảng hốt,<br>        Tìm nhiều chỗ quy y,<br>        Hoặc rừng rậm, núi non,<br>        Hoặc vườn cây, đền tháp.\""},
  {t:"\"Quy y ấy không ổn,<br>        Không quy y tối thượng.<br>        Quy y các chỗ ấy,<br>        Không thoát mọi khổ đau?\""},
  {t:"\"Ai quy y Ðức Phật,<br>        Chánh pháp và chư tăng,<br>        Ai dùng chánh tri kiến,<br>        Thấy được bốn Thánh đế.\""},
  {t:"\"Thấy khổ và khổ tập,<br>        Thấy sự khổ vượt qua,<br>        Thấy đường Thánh tám ngành,<br>        Ðưa đến khổ não tận.\""},
  {t:"\"Thật quy y an ổn,<br>        Thật quy y tối thượng,<br>        Có quy y như vậy,<br>        Mới thoát mọi khổ đau.\""},
  {t:"\"Khó gặp bậc thánh nhơn,<br>        Không phải đâu cũng có.<br>        Chỗ nào bậc trí sanh,<br>        Gia đình tất an lạc.\""},
  {t:"\"Vui thay, Phật ra đời!<br>        Vui thay, Pháp được giảng!<br>        Vui thay, Tăng hòa hợp!<br>        Hòa hợp tu, vui thay!\""},
  {t:"\"Cúng dường bậc đáng cúng,<br>        Chư Phật hoặc đệ tử,<br>        Các bậc vượt hý luận,<br>        Ðoạn diệt mọi sầu bi.\""},
  {t:"\"Cúng dường bậc như vậy,<br>        Tịch tịnh, không sợ hãi,<br>        Các công đức như vậy,<br>        Không ai ước lường được.\""},
  {t:"\"Vui thay, chúng ta sống,<br>        Không hận, giữa hận thù!<br>        Giữa những người thù hận,<br>        Ta sống, không hận thù!\""},
  {t:"\"Vui thay, chúng ta sống,<br>        Không bệnh, giữa ốm đau!<br>        Giữa những người bệnh hoạn,<br>        Ta sống, không ốm đau.\""},
  {t:"\"Vui thay, chúng ta sống,<br>        Không rộn giữa rộn ràng;<br>        Giữa những người rộn ràng,<br>        Ta sống, không rộn ràng.\""},
  {t:"\"Vui thay chúng ta sống,<br>        Không gì, gọi của ta.<br>        Ta sẽ hưởng hỷ lạc,<br>        Như chư thiên Quang Âm.\""},
  {t:"\"Chiến thắng sinh thù oán,<br>        Thất bại chịu khổ đau,<br>        Sống tịch tịnh an lạc.<br>        Bỏ sau mọi thắng bại.\""},
  {t:"\"Lửa nào sánh lửa tham?<br>        Ác nào bằng sân hận?<br>        Khổ nào sánh khổ uẩn,<br>        Lạc nào bằng tịnh lạc.\""},
  {t:"\"Ðói ăn, bệnh tối thượng,<br>        Các hành, khổ tối thượng,<br>        Hiểu như thực là vậy,<br>        Niết Bàn, lạc tối thượng.\""},
  {t:"\"Không bệnh, lợi tối thượng,<br>        Biết đủ, tiền tối thượng,<br>        Thành tín đối với nhau,<br>        Là bà con tối thượng.<br>        Niết Bàn, lạc tối thượng.\""},
  {t:"\"Ðã nếm vị độc cư,<br>        Ðược hưởng vị nhàn tịnh,<br>        Không sợ hãi, không ác,<br>        Nếm được vị pháp hỷ.\""},
  {t:"\"Lành thay, thấy thánh nhân,<br>        Sống chung thường hưởng lạc.<br>        Không thấy những người ngu,<br>        Thường thường được an lạc.\""},
  {t:"\"Sống chung với người ngu,<br>        Lâu dài bị lo buồn.<br>        Khổ thay gần người ngu,<br>        Như thường sống kẻ thù.<br>        Vui thay, gần người trí,<br>        Như chung sống bà con.\""},
  {t:"\"Bậc hiền sĩ, trí tuệ<br>        Bậc nghe nhiều, trì giới,<br>        Bậc tự chế, Thánh nhân;<br>        Hãy gần gũi, thân cận<br>        Thiện nhân, trí giả ấy,<br>        Như trăng theo đường sao.\""},
  {t:"\"Tự chuyên, không đáng chuyên<br>        Không chuyên, việc đáng chuyên.<br>        Bỏ đích, theo hỷ ái,<br>        Ganh tị bậc tự chuyên.\""},
  {t:"\"Chớ gần gũi người yêu,<br>        Trọn đời xa kẻ ghét.<br>        Yêu không gặp là khổ,<br>        Oán phải gặp cũng đau.\""},
  {t:"\"Do vậy chớ yêu ai,<br>        Ái biệt ly là ác;<br>        Những ai không yêu ghét,<br>        Không thể có buộc ràng.\""},
  {t:"\"Do ái sinh sầu ưu,<br>        Do ái sinh sợ hãi,<br>        Ai thoát khỏi tham ái,<br>        Không sầu, đâu sợ hãi?\""},
  {t:"\"Ái luyến sinh sầu ưu,<br>        Ái luyến sinh sợ hãi.<br>        Ai giải thoát ái luyến<br>        Không sầu, đâu sợ hãi?\""},
  {t:"\"Hỷ ái sinh sầu ưu,<br>        Hỷ ái sinh sợ hãi.<br>        Ai giải thoát hỷ ái,<br>        Không sầu, đâu sợ hãi?"},
  {t:"\"Dục ái sinh sầu ưu,<br>        Dục ái sinh sợ hãi,<br>        Ai thoát khỏi dục ái,<br>        Không sầu, đâu sợ hãi?\""},
  {t:"\"Tham ái sinh sầu ưu,<br>        Tham ái sinh sợ hãi.<br>        Ai thoát khỏi tham ái,<br>        Không sầu, đâu sợ hãi.\""},
  {t:"\"Ðủ giới đức, chánh kiến;<br>        Trú pháp, chứng chân lý,<br>        Tự làm công việc mình,<br>        Ðược quần chúng ái kính.\""},
  {t:"\"Ước vọng pháp ly ngôn<br>        Ý cảm xúc thượng quả<br>        Tâm thoát ly ác dục,<br>        Xứng gọi bậc Thượng Lưu.\""},
  {t:"\"Khách lâu ngày ly hương,<br>        An toàn từ xa về,<br>        Bà con cùng thân hữu,<br>        Hân hoan đón chào mừng.\""},
  {t:"\"Cũng vậy các phước nghiệp,<br>        Ðón chào người làm lành,<br>        Ðời này đến đời kia.<br>        Như thân nhân, đón chào.\""},
  {t:"\"Bỏ phẫn nộ, ly mạn,<br>        Vượt qua mọi kiết sử,<br>        Không chấp trước danh sắc.<br>        Khổ không theo vô sản.\""},
  {t:"\"Ai chặn được phẫn nộ,<br>        Như dừng xe đang lăn,<br>        Ta gọi người đánh xe,<br>        Kẻ khác, cầm cương hờ.\""},
  {t:"\"Lấy không giận thắng giận,<br>        Lấy thiện thắng không thiện,<br>        Lấy thí thắng xan tham,<br>        Lấy chơn thắng hư ngụy.\""},
  {t:"\"Nói thật, không phẫn nộ,<br>        Của ít, thí người xin,<br>        Nhờ ba việc lành này,<br>        Người đến gần thiên giới.\""},
  {t:"\"Bậc hiền không hại ai,<br>        Thân thường được chế ngự,<br>        Ðạt được cảnh bất tử,<br>        Ðến đây, không ưu sầu.\""},
  {t:"\"Những người thường giác tỉnh,<br>        Ngày đêm siêng tu học,<br>        Chuyên tâm hướng Niết Bàn,<br>        Mọi lậu hoặc được tiêu.\""},
  {t:"\"A-tu-la, nên biết,<br>        Xưa vậy, nay cũng vậy,<br>        Ngồi im, bị người chê,<br>        Nói nhiều bị người chê.<br>        Nói vừa phải, bị chê.<br>        Làm người không bị chê,<br>        Thật khó tìm ở đời.\""},
  {t:"\"Xưa, vị lai, và nay,<br>        Ðâu có sự kiện này,<br>        Người hoàn toàn bị chê,<br>        Người trọn vẹn được khen.\""},
  {t:"\"Sáng sáng, thẩm xét kỹ.<br>        Bậc có trí tán thán.<br>        Bậc trí không tỳ vết,<br>        Ðầy đủ giới định tuệ.\""},
  {t:"\"Hạnh sáng như vàng ròng,<br>        Ai dám chê vị ấy?<br>        Chư thiên phải khen thưởng,<br>        Phạm Thiên cũng tán dương \"."},
  {t:"\"Giữ thân đừng phẫn nộ,<br>        Phòng thân khéo bảo vệ,<br>        Từ bỏ thân làm ác,<br>        Với thân làm hạnh lành.\""},
  {t:"\"Giữ lời đừng phẫn nộ,<br>        Phòng lời, khéo bảo vệ,<br>        Từ bỏ lời thô ác,<br>        Với lời, nói điều lành.\""},
  {t:"\"Giữ ý đừng phẫn nộ,<br>        Phòng ý, khéo bảo vệ,<br>        Từ bỏ ý nghĩ ác,<br>        Với ý, nghĩ hạnh lành.’"},
  {t:"\"Bậc trí bảo vệ thân,<br>        Bảo vệ luôn lời nói<br>        Bảo vệ cả tâm tư,<br>        Ba nghiệp khéo bảo vệ.\""},
  {t:"\"Ngươi nay giống lá héo,<br>        Diêm sứ đang chờ ngươi,<br>        Ngươi đứng trước cửa chết,<br>        Ðường trường thiếu tư lương.\""},
  {t:"\"Hãy tự làm hòn đảo,<br>        Tinh cần gấp, sáng suốt.<br>        Trừ cấu uế, thanh tịnh,<br>        Ðến Thánh địa chư Thiên.\""},
  {t:"\"Ðời ngươi nay sắp tàn,<br>        Tiến gần đến Diêm Vương.<br>        Giữa đường không nơi nghỉ,<br>        Ðường trường thiếu tư lương.\""},
  {t:"\"Hãy tự làm hòn đảo,<br>        Tinh cần gấp sáng suốt.<br>        Trừ cấu uế, thanh tịnh,<br>        Chẳng trở lại sanh già.\""},
  {t:"\"Bậc trí theo tuần tự.<br>        Từng sát na trừ dần.<br>        Như thợ vàng lọc bụi<br>        Trừ cấu uế nơi mình.\""},
  {t:"\"Như sét từ sắt sanh,<br>        Sắt sanh lại ăn sắt,<br>        Cũng vậy, quá lợi dưỡng<br>        Tự nghiệp dẫn cõi ác.\""},
  {t:"\"Không tụng làm nhớp kinh,<br>        Không đứng dậy, bẩn nhà,<br>        Biếng nhác làm nhơ sắc,<br>        Phóng dật uế người canh\""},
  {t:"\"Tà hạnh nhơ đàn bà,<br>        Xan tham nhớp kẻ thí,<br>        Ác pháp là vết nhơ,<br>        Ðời này và đời sau.\""},
  {t:"\"Trong hàng cấu uế ấy,<br>        Vô minh, nhơ tối thượng,<br>        Ðoạn nhơ ấy, tỷ kheo,<br>        Thành bậc không uế nhiễm.\""},
  {t:"\"Dễ thay, sống không hổ<br>        Sống lỗ mãng như quạ,<br>        Sống công kích huênh hoang,<br>        Sống liều lĩnh, nhiễm ô.\""},
  {t:"\"Khó thay, sống xấu hổ,<br>        Thường thường cầu thanh tịnh.<br>        Sống vô tư, khiêm tốn,<br>        Trong sạch và sáng suốt.\""},
  {t:"\"Ai ở đời sát sinh,<br>        Nói láo không chân thật,<br>        Ở đời lấy không cho,<br>        Qua lại với vợ người.\""},
  {t:"\"Uống rượu men, rượu nấu,<br>        Người sống đam mê vậy,<br>        Chính ngay tại đời này,<br>        Tự đào bới gốc mình.\""},
  {t:"\"Vậy người, hãy nên biết,<br>        Không chế ngự là ác.<br>        Chớ để tham phi pháp,<br>        Làm người đau khổ dài.\""},
  {t:"\"Do tín tâm, hỷ tâm<br>        Loài người mới bố thí.<br>        Ở đây ai bất mãn<br>        Người khác được ăn uống,<br>        Người ấy ngày hoặc đêm,<br>        Không đạt được tâm định?\""},
  {t:"\"Ai cắt được, phá được,<br>        Tận gốc nhổ tâm ấy.<br>        Người ấy ngày hoặc đêm,<br>        Ðạt được tâm thiền định.\""},
  {t:"\"Lửa nào bằng lửa tham!<br>        Chấp nào bằng sân hận!<br>        Lưới nào bằng lưới si!<br>        Sông nào bằng sông ái! \""},
  {t:"\"Dễ thay thấy lỗi người,<br>        Lỗi mình thấy mới khó.<br>        Lỗi người ta phanh tìm,<br>        Như sàng trấu trong gạo,<br>        Còn lỗi mình, che đậy,<br>        Như kẻ gian dấu bài.\""},
  {t:"\"Ai thấy lỗi của người,<br>        Thường sanh lòng chỉ trích,<br>        Người ấy lậu hoặc tăng,<br>        Rất xa lậu hoặc diệt.\""},
  {t:"\"Hư không, không dấu chân,<br>        Ngoài đây, không sa môn,<br>        Chúng sanh thích hý luận,<br>        Như lai, hý luận trừ.\""},
  {t:"\"Hư không, không dấu chân,<br>        Ngoài đây, không sa môn.<br>        Các hành không thường trú,<br>        Chư Phật không giao động.\""},
  {t:"\"Ngươi đâu phải pháp trụ,<br>        Xử sự quá chuyên chế,<br>        Bậc trí cần phân biệt<br>        Cả hai chánh và tà!\""},
  {t:"\"Không chuyên chế, đúng pháp,<br>        Công bằng, dắt dẫn người,<br>        Bậc trí sống đúng pháp,<br>        Thật xứng danh pháp trụ.\""},
  {t:"\"Không phải vì nói nhiều,<br>        Mới xứng danh bậc trí.<br>        An ổn, không oán sợ.<br>        Thật đáng gọi bậc trí.\""},
  {t:"\"Không phải vì nói nhiều,<br>        Mới xứng danh trì pháp,<br>        Những ai tuy nghe ít,<br>        Nhưng thân hành đúng pháp,<br>        Không phóng túng chánh pháp,<br>        Mới xứng danh trì pháp.\""},
  {t:"\"Không phải là trưởng lão,<br>        Dầu cho có bạc đầu.<br>        Người chỉ tuổi tác cao,<br>        Ðược gọi là: \"Lão ngu.\""},
  {t:"\"Ai chân thật, đúng pháp,<br>        Không hại, biết chế phục,<br>        Bậc trí không cấu uế,<br>        Mới xứng danh Trưởng Lão.\""},
  {t:"\"Không phải nói lưu loát,<br>        Không phải sắc mặt đẹp,<br>        Thành được người lương thiện,<br>        Nếu ganh, tham, dối trá.\""},
  {t:"\"Ai cắt được, phá được<br>        Tận gốc nhổ tâm ấy<br>        Người trí ấy diệt sân,<br>        Ðược gọi người hiền thiện.\""},
  {t:"\"Ðầu trọc, không sa môn<br>        Nếu phóng túng, nói láo.<br>        Ai còn đầy dục tham,<br>        Sao được gọi sa môn?\""},
  {t:"\"Ai lắng dịu hoàn toàn,<br>        Các điều ác lớn nhỏ,<br>        Vì lắng dịu ác pháp,<br>        Ðược gọi là Sa môn.\""},
  {t:"\"Chỉ khất thực nhờ người,<br>        Ðâu phải là tỷ kheo!<br>        Phải theo pháp toàn diện,<br>        Khất sĩ không, không đủ.\""},
  {t:"\"Ai vượt qua thiện ác,<br>        Chuyên sống đời Phạm Hạnh,<br>        Sống thẩm sát ở đời,<br>        Mới xứng danh tỷ kheo.\""},
  {t:"\"Im lặng nhưng ngu si,<br>        Ðâu được gọi ẩn sĩ?<br>        Như người cầm cán cân,<br>        Bậc trí chọn điều lành.\""},
  {t:"\"Từ bỏ các ác pháp,<br>        Mới thật là ẩn sĩ.<br>        Ai thật hiểu hai đời<br>        Mới được gọi ẩn sĩ.\""},
  {t:"\"Còn sát hại sinh linh,<br>        Ðâu được gọi Hiền thánh.<br>        Không hại mọi hữu tình,<br>        Mới được gọi Hiền Thánh.\""},
  {t:"\"Chẳng phải chỉ giới cấm<br>        Cũng không phải học nhiều,<br>        Chẳng phải chứng thiền định,<br>        Sống thanh vắng một mình.\""},
  {t:"\"Ta hưởng an ổn lạc,<br>        Phàm phu chưa hưởng được.<br>        Tỷ kheo, chớ tự tin<br>        Khi lậu hoặc chưa diệt.\""},
  {t:"\"Tám chánh, đường thù thắng,<br>        Bốn câu, lý thù thắng.<br>        Ly tham, pháp thù thắng,<br>        Giữa các loài hai chân,<br>        Pháp nhãn, người thù thắng.\""},
  {t:"\"Ðường này, không đường khác<br>        Ðưa đến kiến thanh tịnh.<br>        Nếu ngươi theo đường này,<br>        Ma quân sẽ mê loạn.\""},
  {t:"\"Nếu người theo đường này,<br>        Ðau khổ được đoạn tận.<br>        Ta dạy người con đường.<br>        Với trí, gai chướng diệt.\""},
  {t:"\"Người hãy nhiệt tình làm,<br>        Như Lai chỉ thuyết dạy.<br>        Người hành trì thiền định<br>        Thoát trói buộc Ác ma.\""},
  {t:"\"Tất cả hành vô thường \"<br>        Với Tuệ, quán thấy vậy<br>        Ðau khổ được nhàm chán;<br>        Chính con đường thanh tịnh.\""},
  {t:"\"Tất cả hành khổ đau<br>        Với Tuệ quán thấy vậy,<br>        Ðau khổ được nhàm chán;<br>        Chính con đường thanh tịnh.\""},
  {t:"\"Tất cả pháp vô ngã,<br>        Với Tuệ quán thấy vậy,<br>        Ðau khổ được nhàm chán<br>        Chính con đường thanh tịnh.\""},
  {t:"\"Khi cần, không nỗ lực,<br>        Tuy trẻ mạnh, nhưng lười<br>        Chí nhu nhược, biếng nhác.<br>        Với trí tuệ thụ động,<br>        Sao tìm được chánh đạo?\""},
  {t:"\"Lời nói được thận trọng,<br>        Tâm tư khéo hộ phòng,<br>        Thân chớ làm điều ác,<br>        Hãy giữ ba nghiệp tịnh,<br>        Chứng đạo thánh nhân dạy.\""},
  {t:"\"Tu thiền, trí tuệ sanh,<br>        Bỏ Thiền, trí tuệ diệt.<br>        Biết con đường hai ngả<br>        Ðưa đến hữu, phi hữu,<br>        Hãy tự mình nỗ lực,<br>        Khiến trí tuệ tăng trưởng.\""},
  {t:"\"Ðốn rừng không đốn cây<br>        Từ rừng, sinh sợ hãi;<br>        Ðốn rừng và ái dục,<br>        Tỷ kheo, hãy tịch tịnh.\""},
  {t:"\"Khi nào chưa cắt tiệt,<br>        Ái dục giữa gái trai,<br>        Tâm ý vẫn buộc ràng,<br>        Như bò con vú mẹ.\""},
  {t:"\"Tự cắt giây ái dục,<br>        Như tay bẻ sen thu,<br>        Hãy tu đạo tịch tịnh,<br>        Niết-Bàn, Thiện Thệ dạy.\""},
  {t:"\"Mùa mưa ta ở đây<br>        Ðông, hạ cũng ở đây,<br>        Người ngu tâm tưởng vậy,<br>        Không tự giác hiểm nguy.\""},
  {t:"\"Người tâm ý đắm say<br>        Con cái và súc vật,<br>        Tử thần bắt người ấy,<br>        Như lụt trôi làng ngủ. \""},
  {t:"\"Một khi tử thần đến,<br>        Không có con che chở,<br>        Không cha, không bà con,<br>        Không thân thích che chở.\""},
  {t:"\"Biết rõ ý nghĩa này,<br>        Bậc trí lo trì giới,<br>        Mau lẹ làm thanh tịnh,<br>        Con đường đến Niết-Bàn.\""},
  {t:"\"Nhờ từ bỏ lạc nhỏ,<br>        Thấy được lạc lớn hơn,<br>        Bậc trí bỏ lạc nhỏ,<br>        Thấy được lạc lớn hơn.\""},
  {t:"\"Gieo khổ đau cho người,<br>        Mong cầu lạc cho mình,<br>        Bị hận thù buộc ràng<br>        Không sao thoát hận thù.\""},
  {t:"\"Việc đáng làm, không làm,<br>        Không đáng làm, lại làm,<br>        Người ngạo mạn, phóng dật,<br>        Lậu hoặc ắt tăng trưởng.\""},
  {t:"\"Người siêng năng cần mẫn,<br>        Thường thường quán thân niệm,<br>        Không làm việc không đáng,<br>        Gắng làm việc đáng làm,<br>        Người tư niệm giác tỉnh,<br>        Lậu hoặc được tiêu trừ.\""},
  {t:"\"Sau khi giết mẹ cha,<br>        Giết hai Vua Sát lỵ,<br>        Giết vương quốc, quần thần<br>        Vô ưu, phạm chí sống.\""},
  {t:"\"Sau khi giết mẹ cha,<br>        Hai vua Bà-la-môn,<br>        Giết hổ tướng thứ năm<br>        Vô ưu, phạm chí sống.\""},
  {t:"\"Ðệ tử Gotama,<br>        Luôn luôn tự tỉnh giác<br>        Vô luận ngày hay đêm,<br>        Tưởng Phật Ðà thường niệm.\""},
  {t:"\"Ðệ tử Gotama,<br>        Luôn luôn tự tỉnh giác,<br>        Vô luận ngày hay đêm,<br>        Tưởng Chánh Pháp thường niệm\""},
  {t:"\"Ðệ tử Gotama,<br>        Luôn luôn tự tỉnh giác,<br>        Vô luận ngày hay đêm,<br>        Tưởng Tăng Già thường niệm.\""},
  {t:"\"Ðệ tử Gotama,<br>        Luôn luôn tự tỉnh giác,<br>        Vô luận ngày hay đêm,<br>        Tưởng sắc thân thường niệm.\""},
  {t:"\"Ðệ tử Gotama,<br>        Luôn luôn tự tỉnh giác,<br>        Vô luận ngày hay đêm,<br>        Ý vui niềm bất hại.\""},
  {t:"\"Ðệ tử Gotama,<br>        Luôn luôn tự tỉnh giác,<br>        Vô luận ngày hay đêm,<br>        Ý vui tu thiền quán.\""},
  {t:"\"Vui hạnh xuất gia khó,<br>        Tại gia sinh hoạt khó,<br>        Sống bạn không đồng, khổ,<br>        Trôi lăn luân hồi, khổ,<br>        Vậy chớ sống luân hồi,<br>        Chớ chạy theo đau khổ.\""},
  {t:"\"Tín tâm, sống giới hạnh<br>        Ðủ danh xưng tài sản,<br>        Chỗ nào người ấy đến,<br>        Chỗ ấy được cung kính.\""},
  {t:"\"Người lành dầu ở xa<br>        Sáng tỏ như núi tuyết,<br>        Người ác dầu ở gần<br>        Như tên bắn đêm đen.\""},
  {t:"\"Ai ngồi nằm một mình.<br>        Ðộc hành không buồn chán,<br>        Tự điều phục một mình<br>        Sống thoải mái rừng sâu.\""},
  {t:"\"Nói láo đọa địa ngục<br>        Có làm nói không làm,<br>        Cả hai chết đồng đẳng,<br>       Làm người, nghiệp hạ liệt.\""},
  {t:"\"Nhiều người khoác cà sa,<br>        Ác hạnh không nhiếp phục.<br>        Người ác, do ác hạnh,<br>        Phải sanh cõi Ðịa ngục.\""},
  {t:"\"Tốt hơn nuốt hòn sắt<br>        Cháy đỏ như lửa hừng,<br>        Hơn ác giới, buông lung<br>        Ăn đồ ăn quốc độ.\""},
  {t:"\"Bốn nạn chờ đợi người,<br>        Phóng dật theo vợ người;<br>        Mắc họa, ngủ không yên,<br>        Bị chê là thứ ba,<br>        Ðọa địa ngục, thứ bốn.\""},
  {t:"\"Mắc họa, đọa ác thú,<br>        Bị hoảng sợ, ít vui.<br>        Quốc vương phạt trọng hình.<br>        Vậy chớ theo vợ người.\""},
  {t:"\"Như cỏ sa vụng nắm,<br>        Tất bị họa đứt tay<br>        Hạnh Sa môn tà vạy,<br>        Tất bị đọa địa ngục.\""},
  {t:"\"Sống phóng đãng buông lung,<br>        Theo giới cấm ô nhiễm,<br>        Sống Phạm hạnh đáng nghi<br>        Sao chứng được quả lớn?"},
  {t:"\"Cần phải làm, nên làm<br>        Làm cùng tận khả năng<br>        Xuất gia sống phóng đãng,<br>        Chỉ tăng loạn bụi đời.\""},
  {t:"\"Ác hạnh không nên làm,<br>        Làm xong, chịu khổ lụy,<br>        Thiện hạnh, ắt nên làm,<br>        Làm xong, không ăn năn.\""},
  {t:"\"Như thành ở biên thùy,<br>        Trong ngoài đều phòng hộ<br>        Cũng vậy, phòng hộ mình,<br>        Sát na chớ buông lung.<br>        Giây phút qua, sầu muộn.<br>        Khi rơi vào địa ngục.\""},
  {t:"\"Không đáng hổ, lại hổ.<br>        Việc đáng hổ, lại không.<br>        Do chấp nhận tà kiến,<br>        Chúng sanh đi ác thú.\""},
  {t:"\"Không đáng sợ, lại sợ,<br>        Ðáng sợ, lại thấy không,<br>        Do chấp nhận tà kiến.<br>        Chúng sanh đi ác thú.\""},
  {t:"\"Không lỗi, lại thấy lỗi,<br>        Có lỗi, lại thấy không,<br>        Do chấp nhận tà kiến,<br>        Chúng sanh đi ác thú.\""},
  {t:"\"Có lỗi, biết có lỗi,<br>        Không lỗi, biết là không,<br>        Do chấp nhận chánh kiến,<br>        Chúng sanh đi cõi lành.\""},
  {t:"\"Ta như voi giữa trận,<br>        Hứng chịu cung tên rơi,<br>        Chịu đựng mọi phỉ báng.<br>        Ác giới rất nhiều người.\""},
  {t:"\"Voi luyện, đưa dự hội,<br>        Ngựa luyện, được vua cưỡi,<br>        Người luyện, bậc tối thượng<br>        Chịu đựng mọi phỉ báng.\""},
  {t:"\"Tốt thay, con la thuần,<br>        Thuần chủng loài ngựa Sin.<br>        Ðại tượng, voi có ngà.<br>        Tự điều mới tối thượng.\""},
  {t:"\"Chẳng phải loài cưỡi ấy,<br>        Ðưa người đến Niết-Bàn,<br>        Chỉ có người tự điều,<br>        Ðến đích, nhờ điều phục.\""},
  {t:"\"Con voi tên Tài Hộ,<br>        Phát dục, khó điều phục,<br>        Trói buộc, không ăn uống.<br>        Voi nhớ đến rừng voi.\""},
  {t:"\"Người ưa ngủ, ăn lớn<br>        Nằm lăn lóc qua lại,<br>        Chẳng khác heo no bụng,<br>        Kẻ ngu nhập thai mãi.\""},
  {t:"\"Trước tâm này buông lung,<br>        Chạy theo ái, dục, lạc.<br>        Nay Ta chánh chế ngự,<br>        Như cầm móc điều voi.\""},
  {t:"\"Hãy vui không phóng dật,<br>        Khéo phòng hộ tâm ý.<br>        Kéo mình khỏi ác đạo,<br>        Như voi bị sa lầy.\""},
  {t:"\"Nếu được bạn hiền trí<br>        Ðáng sống chung, hạnh lành,<br>        Nhiếp phục mọi hiểm nguy<br>        Hoan hỷ sống chánh niệm.\""},
  {t:"\"Không gặp bạn hiền trí.<br>        Ðáng sống chung, hạnh lành<br>        Như vua bỏ nước bại,<br>        Hãy sống riêng cô độc,<br>        Như voi sống rừng voi.\""},
  {t:"\"Tốt Hơn sống một mình,<br>        Không kết bạn người ngu.<br>        Ðộc thân, không ác hạnh<br>        Sống vô tư vô lự,<br>        Như voi sống rừng voi.\""},
  {t:"\"Vui thay, bạn lúc cần!<br>        Vui thay, sống biết đủ,<br>        Vui thay, chết có đức!<br>        Vui thay, mọi khổ đoạn.\""},
  {t:"\"Vui thay, hiếu kính mẹ,<br>        Vui thay, hiếu kính cha,<br>        Vui thay, kính Sa môn,<br>        Vui thay, kính Hiền Thánh.\""},
  {t:""},
  {t:"\"Ta hàng phục tất cả,<br>        Ta rõ biết tất cả,<br>        Không bị nhiễm pháp nào.<br>        Ta từ bỏ tất cả<br>        Ái diệt, tự giải thoát.<br>        Ðã tự mình thắng trí,<br>        Ta gọi ai thầy ta?\""},
  {t:"\"Pháp thí, thắng mọi thí!<br>        Pháp vị, thắng mọi vị!<br>        Pháp hỷ, thắng mọi hỷ!<br>        Ái diệt, dứt mọi khổ!\""},
  {t:"\"Tài sản hại người ngu.<br>        Không người tìm bờ kia<br>        Kẻ ngu vì tham giàu,<br>        Hại mình và hại người.\""},
  {t:"\"Cỏ làm hại ruộng vườn,<br>        Tham làm hại người đời.<br>        Bố thí người ly tham,<br>        Do vậy được quả lớn.\""},
  {t:"\"Cỏ làm hại ruộng vườn,<br>        Sân làm hại người đời.<br>        Bố thí người ly sân,<br>        Do vậy được quả lớn.\""},
  {t:"\"Cỏ làm hại ruộng vườn,<br>        Si làm hại người đời,<br>        Bố thí người ly si,<br>        Do vậy được quả lớn.\""},
  {t:"\"Cỏ làm hại ruộng vườn,<br>        Dục làm hại người đời.<br>        Bố thí người ly dục,<br>        Do vậy được quả lớn.\""},
  {t:"\"Lành thay, phòng hộ mắt!<br>        Lành thay, phòng hộ tai.<br>        Lành thay, phòng hộ mũi,<br>        Lành thay, phòng hộ lưỡi.\""},
  {t:"\"Lành thay, phòng hộ thân!<br>        Lành thay, phòng hộ lời,<br>        Lành thay, phòng hộ ý.<br>        Lành thay, phòng tất cả.<br>        Tỷ kheo phòng tất cả.<br>        Thoát được mọi khổ đau.\""},
  {t:"\"Người chế ngự tay chân,<br>        Chế ngự lời và đầu,<br>        Vui thích nội thiền định.<br>        Ðộc thân, biết vừa đủ,<br>        Thật xứng gọi tỷ kheo.\""},
  {t:"\"Tỷ kheo chế ngự miệng,<br>        Vừa lời, không cống cao,<br>        Khi trình bày pháp nghĩa,<br>        Lời lẽ dịu ngọt ngào.\""},
  {t:"\"Vị tỷ kheo thích pháp,<br>        Mến pháp, suy tư Pháp.<br>        Tâm tư niệm chánh Pháp,<br>        Không rời bỏ chánh Pháp.\""},
  {t:"\"Không khinh điều mình được,<br>        Không ganh người khác được<br>        Tỷ kheo ganh tị người,<br>        Không sao chứng Thiền Ðịnh.\""},
  {t:"\"Tỷ kheo dầu được ít,<br>        Không khinh điều mình được,<br>        Sống thanh tịnh không nhác,<br>        Chư thiên khen vị này.\""},
  {t:"\"Hoàn toàn, đối danh sắc,<br>        Không chấp Ta, của Ta.<br>        Không chấp, không sầu não.<br>        Thật xứng danh Tỷ kheo.\""},
  {t:"\"Tỷ kheo trú từ bi,<br>        Tín thành giáo Pháp Phật,<br>        Chứng cảnh giới tịch tỉnh.<br>        Các hạnh an tịnh lạc.\""},
  {t:"\"Tỷ-kheo, tát thuyền này,<br>        Thuyền không, nhẹ đi mau.<br>        Trừ tham, diệt sân hận,<br>        Tất chứng đạt Niết-Bàn.\""},
  {t:"\"Ðoạn năm, từ bỏ năm<br>        Tụ tập năm tối thượng<br>        Tỷ kheo vượt năm ái<br>        Xứng danh \"Vượt bộc lưu\""},
  {t:"\"Tỷ kheo, hãy tu thiền,<br>        Chớ buông lung phóng dật,<br>        Tâm chớ đắm say dục,<br>        Phóng dật, nuốt sắt nóng<br>        Bị đốt, chớ than khổ!\""},
  {t:"\"Không trí tuệ, không thiền,<br>        Không thiền, không trí tuệ.<br>        Người có thiền có tuệ,<br>        Nhất định gần Niết-Bàn.\""},
  {t:"\"Bước vào ngôi nhà trống,<br>        Tỷ kheo tâm an tịnh,<br>        Thọ hưởng vui siêu nhân<br>        Tịnh quán theo chánh pháp.\""},
  {t:"\"Người luôn luôn chánh niệm,<br>        Sự sanh diệt các uẩn,<br>        Ðược hoan hỷ, hân hoan,<br>        Chỉ bậc bất tử biết.\""},
  {t:"\"Ðây Tỷ kheo có trí,<br>        Tụ tập pháp căn bản<br>        Hộ căn, biết vừa đủ,<br>        Giữ gìn căn bản giới,<br>        Thường gần gũi bạn lành,<br>        Sống thanh tịnh tinh cần.\""},
  {t:"\"Giao thiệp khéo thân thiện,<br>        Cử chỉ mực đoan trang.<br>  Vui thay, già có giới!<br>        Vui thay, tín an trú!<br>        Vui thay, được trí tuệ,<br>        Vui thay, ác không làm.\""},
  {t:"\"Người sống đời phóng dật,<br>        Ái tăng như giây leo.<br>        Nhảy đời này đời khác,<br>        Như vượn tham quả rừng.\""},
  {t:"\"Ai sống trong đời này,<br>        Bị ái dục buộc ràng<br>        Sầu khổ sẽ tăng trưởng,<br>        Như cỏ Bi gặp mưa.\""},
  {t:"\"Ai sống trong đời này<br>        Ái dục được hàng phục<br>        Sầu rơi khỏi người ấy<br>        Như giọt nước lá sen.\""},
  {t:"\"Ðây điều lành Ta dạy,<br>        Các người tụ họp đây.<br>        Hãy nhổ tận gốc ái<br>        Như nhổ gốc cỏ Bi.<br>        Chớ để ma phá hoại,<br>        Như giòng nước cỏ lau.\""},
  {t:"\"Như cây bị chặt đốn,<br>        Gốc chưa hại vẫn bền<br>        Ái tùy miên chưa nhổ,<br>        Khổ này vẫn sanh hoài.\""},
  {t:"\"Ba mươi sáu dòng Ái,<br>        Trôi người đốn khả ái.<br>        Các tư tưởng tham ái.<br>        Cuốn trôi người tà kiến.\""},
  {t:"\"Dòng ái dục chảy khắp,<br>        Như giây leo mọc tràn,<br>        Thấy giây leo vừa sanh,<br>        Với tuệ, hãy đoạn gốc.\""},
  {t:"\"Người đời nhớ ái dục,<br>        Ưa thích các hỷ lạc.<br>        Tuy mong cầu an lạc,<br>        Họ vẫn phải sanh già.\""},
  {t:"\"Người bị ái buộc ràng,<br>        Vùng vẫy và hoảng sợ,<br>        Như thỏ bị sa lưới.<br>        Họ sanh ái trói buộc,<br>        Chịu khổ đau dài dài.\""},
  {t:"\"Người bị ái buộc ràng,<br>        Vùng vẫy và hoảng sợ,<br>        Như thỏ bị sa lưới.<br>        Do vậy vị tỷ kheo,<br>        Mong cầu mình ly tham<br>        Nên nhiếp phục ái dục.\""},
  {t:"\"Lìa rừng lại hướng rừng<br>        Thoát rừng chạy theo rừng.<br>        Nên xem người như vậy,<br>        Ðược thoát khỏi buộc ràng.<br>        Lại chạy theo ràng buộc.\""},
  {t:"\"Sắt, cây, gai trói buộc<br>        Người trí xem chưa bền.<br>        Tham châu báu, trang sức<br>        Tham vọng vợ và con.\""},
  {t:"\"Người có trí nói rằng:<br>        \"Trói buộc này thật bền.<br>        Rì kéo xuống, lún xuống,<br>        Nhưng thật sự khó thoát.<br>        Người trí cắt trừ nó,<br>        Bỏ dục lạc, không màng.\""},
  {t:"\"Người đắm say ái dục<br>        Tự lao mình xuống dòng<br>        Như nhện sa lưới dệt.<br>        Người trí cắt trừ nó,<br>        Bỏ mọi khổ, không màng.\""},
  {t:"\"Bỏ quá, hiện, vị lai,<br>        Ðến bờ kia cuộc đời,<br>        Ý giải thoát tất cả,<br>        Chớ vướng lại sanh già.\""},
  {t:"\"Người tà ý nhiếp phục,<br>        Tham sắc bén nhìn tịnh,<br>        Người ấy ái tăng trưởng,<br>        Làm giây trói mình chặt.\""},
  {t:"\"Ai vui, an tịnh ý,<br>        Quán bất tịnh, thường niệm,<br>        Người ấy sẽ diệt ái,<br>        Cắt đứt Ma trói buộc.\""},
  {t:"\"Ai tới đích, không sợ,<br>        Ly ái, không nhiễm ô<br>        Nhổ mũi tên sanh tử,<br>        Thân này thân cuối cùng.\""},
  {t:"\"\"Giao thiệp khéo thân thiện,<br>        Cử chỉ mực đoan trang.<br>        Do vậy hưởng vui nhiều,<br>        Sẽ dứt mọi khổ đau.\""},
  {t:"\"Như hoa Vassikà,<br>        Quăng bỏ cánh úa tàn,<br>        Cũng vậy vị Tỷ kheo,<br>        Hãy giải thoát tham sân.\""},
  {t:"\"Thân tịnh, lời an tịnh,<br>        An tịnh, khéo thiền tịnh.<br>        Tỷ kheo bỏ thế vật,<br>        Xứng danh \"bậc tịch tịnh \"."},
  {t:"\"Tự mình chỉ trích mình,<br>        Tự mình dò xét mình,<br>        Tỷ kheo tự phòng hộ<br>        Chánh niệm, trú an lạc.\""},
  {t:"\"Tự mình y chỉ mình,<br>        Tự mình đi đến mình,<br>        Vậy hãy tự điều phục,<br>        Như khách buôn ngựa hiền.\""},
  {t:"\"Tỷ kheo nhiều hân hoan,<br>        Tịnh tín giáo pháp Phật,<br>        Chứng cảnh giới tịch tịnh,<br>        Các hạnh an tịnh lạc.\""},
  {t:"\"Tỷ kheo tuy tuổi nhỏ<br>        Siêng tu giáo pháp Phật,<br>        Soi sáng thế gian này,<br>        Như trăng thoát khỏi mây.\""},
  {t:"\"Hỡi này Bà là môn,<br>        Hãy tinh tấn đoạn dòng,<br>        Từ bỏ các dục lạc,<br>        Biết được hành đoạn diệt,<br>        Người là bậc vô vi.\""},
  {t:"\"Nhờ thường trú hai pháp<br>        Ðến được bờ bên kia.<br>        Bà-la-môn có trí,<br>        Mọi kiết sử dứt sạch.\""},
  {t:"\"Không bờ này, bờ kia<br>        Cả hai bờ không có,<br>        Lìa khổ, không trói buộc<br>        Ta gọi Bà-la-môn.\""},
  {t:"\"Tu thiền, trú ly trần<br>        Phận sự xong, vô lậu,<br>        Ðạt được đích tối thượng,<br>        Ta gọi Bà-la-môn.\""},
  {t:"\"Mặt trời sáng ban ngày,<br>        Mặt trăng sáng ban đêm.<br>        Khí giới sáng Sát lỵ,<br>        Thiền định sáng Phạm chí.<br>        Còn hào quang đức Phật,<br>        Chói sáng cả ngày đêm.\""},
  {t:"\"Dứt ác gọi Phạm chí,<br>        Tịnh hạnh gọi Sa môn,<br>        Tự mình xuất cấu uế,<br>        Nên gọi bậc xuất gia.\""},
  {t:"\"Chớ có đập Phạm chí!<br>        Phạm chí chớ đập lại!<br>        Xấu thay đập Phạm chí<br>        Ðập trả lại xấu hơn!\""},
  {t:"\"Ðối vị Bà-la-môn,<br>        Ðây không lợi ích nhỏ.<br>        Khi ý không ái luyến,<br>        Tâm hại được chặn đứng,<br>        Chỉ khi ấy khổ diệt,\""},
  {t:"\"Với người thân miệng ý,<br>        Không làm các ác hạnh<br>        Ba nghiệp được phòng hộ,<br>        Ta gọi Bà-la-môn.\""},
  {t:"\"Từ ai, biết chánh pháp<br>        Bậc Chánh Giác thuyết giảng,<br>        Hãy kính lễ vị ấy,<br>        Như phạm chí chờ lửa.\""},
  {t:"\"Ðược gọi Bà-la-môn,<br>        Không vì đầu bện tóc,<br>        Không chủng tộc, thọ sanh,<br>        Ai thật chân, chánh, tịnh,<br>        Mới gọi Bà-la-môn.\""},
  {t:"\"Kẻ ngu, có ích gì<br>        Bện tóc với da dê,<br>        Nội tâm toàn phiền não,<br>        Ngoài mặt đánh bóng suông.\""},
  {t:"\"Người mặc áo đống rác,<br>        Gầy ốm, lộ mạch gân,<br>        Ðộc thân thiền trong rừng.<br>        Ta gọi Bà-la-môn.\""},
  {t:"\"Ta không gọi Phạm Chí,<br>        Vì chỗ sanh, mẹ sanh.<br>        Chỉ được gọi tên suông<br>        Nếu tâm còn phiền não.<br>        Không phiền não, chấp trước<br>        Ta gọi Bà-la-môn.\""},
  {t:"\"Ðoạn hết các kiết sử,<br>        Không còn gì lo sợ<br>        Không đắm trước buộc ràng<br>        Ta gọi Bà-la-môn"},
  {t:"\"Bỏ đai da, bỏ cương<br>        Bỏ dây, đồ sở thuộc,<br>        Bỏ then chốt, sáng suốt,<br>        Ta gọi Bà-la-môn.\""},
  {t:"\"Không ác ý, nhẫn chịu,<br>        Phỉ báng, đánh, phạt hình,<br>        Lấy nhẫn làm quân lực,<br>        Ta gọi Bà-la-môn.\""},
  {t:"\"Không hận, hết bổn phận,<br>        Trì giới, không tham ái,<br>        Nhiếp phục, thân cuối cùng,<br>        Ta gọi Bà-la-môn.\""},
  {t:"\"Như nước trên lá sen,<br>        Như hột cải đầu kim,<br>        Người không nhiễm ái dục,<br>        Ta gọi Bà-la-môn.\""},
  {t:"\"Ai tự trên đời này,<br>        Giác khổ, diệt trừ khổ,<br>        Bỏ gánh nặng, giải thoát,<br>        Ta gọi Bà-la-môn.\""},
  {t:"\"Người trí tuệ sâu xa,<br>        Khéo biết đạo, phi đạo<br>        Chứng đạt đích vô thượng,<br>        Ta gọi Bà-la-môn.\""},
  {t:"\"Không liên hệ cả hai,<br>        Xuất gia và thế tục,<br>        Sống độc thân, ít dục,<br>        Ta gọi Bà-la-môn.\""},
  {t:"\"Bỏ trượng, đối chúng sanh,<br>        Yếu kém hay kiên cường,<br>        Không giết, không bảo giết,<br>        Ta gọi Bà-la-môn.\""},
  {t:"\"Thân thiện giữa thù địch<br>        Ôn hòa giữa hung hăng.<br>        Không nhiễm, giữa nhiễm trước,<br>        Ta gọi Bà-la-môn.\""},
  {t:"\"Người bỏ rơi tham sân,<br>        Không mạn không ganh tị,<br>        Như hột cải đầu kim,<br>        Ta gọi Bà-la-môn.\""},
  {t:"\"Nói lên lời ôn hòa,<br>        Lợi ích và chân thật,<br>        Không mất lòng một ai,<br>        Ta gọi Bà-la-môn.\""},
  {t:"\"Ở đời, vật dài, ngắn,<br>        Nhỏ, lớn, đẹp hay xấu<br>        Phàm không cho không lấy,<br>        Ta gọi Bà-la-môn.\""},
  {t:"\"Người không có hy cầu,<br>        Ðời này và đời sau,<br>        Không hy cầu, giải thoát,<br>        Ta gọi Bà-la-môn.\""},
  {t:"\"Người không còn tham ái,<br>        Có trí, không nghi hoặc,<br>        Thể nhập vào bất tử,<br>        Ta gọi Bà-la-môn.\""},
  {t:"\"Người sống ở đời này<br>        Không nhiễm cả thiện ác,<br>        Không sầu, sạch không bụi<br>        Ta gọi Bà-la-môn.\""},
  {t:"\"Như trăng, sạch không uế<br>        Sáng trong và tịnh lặng,<br>        Hữu ái, được đoạn tận,<br>        Ta gọi Bà là môn.\""},
  {t:"\"Vượt đường nguy hiểm này,<br>        Nhiếp phục luân hồi, si,<br>        Ðến bờ kia thiền định<br>        Không dục ái, không nghi,<br>        Không chấp trước, tịch tịnh,<br>        Ta gọi Bà-la-môn.\""},
  {t:"\"Ai ở đời, đoạn dục,<br>        Bỏ nhà, sống xuất gia,<br>        Dục hữu được đoạn tận,<br>        Ta gọi Bà-la-môn.\""},
  {t:"\"Ai ở đời đoạn ái<br>        Bỏ nhà, sống xuất gia,<br>        Ái hữu được đoạn tận,<br>        Ta gọi Bà-la-môn.\""},
  {t:"\"Bỏ trói buộc loài người,<br>        Vượt trói buộc cõi trời.<br>        Giải thoát mọi buộc ràng,<br>        Ta gọi Bà-la-môn.\""},
  {t:"\"Bỏ điều ưa, điều ghét,<br>        Mát lạnh, diệt sanh y<br>        Bậc anh hùng chiến thắng,<br>        Nhiếp phục mọi thế giới,<br>        Ta gọi Bà-la-môn.\""},
  {t:"\"Ai hiểu rõ hoàn toàn<br>        Sanh tử các chúng sanh,<br>        Không nhiễm, khéo vượt qua,<br>        Sáng suốt chân giác ngộ,<br>        Ta gọi Bà-la-môn.\""},
  {t:"\"Với ai, loài trời, người<br>        Cùng với Càn thát bà,<br>        Không biết chỗ thọ sanh<br>        Lậu tận bậc La hán.<br>        Ta gọi Bà-la-môn.\""},
  {t:"\"Ai quá, hiện, vị lai<br>        Không một sở hữu gì,<br>        Không sở hữu không nắm,<br>        Ta gọi Bà-la-môn.\""},
  {t:"\"Bậc trâu chúa, thù thắng<br>        Bậc anh hùng, đại sĩ,<br>        Bậc chiến thắng, không nhiễm,<br>        Bậc tẩy sạch, giác ngộ,<br>        Ta gọi Bà-la-môn.\""},
  {t:"\"Ai biết được đời trước,<br>        Thấy thiên giới, đọa xứ,<br>        Ðạt được sanh diệt tận<br>        Thắng trí, tự viên thành<br>        Bậc mâu ni đạo sĩ.<br>        Viên mãn mọi thành tựu<br>        Ta gọi Bà-la-môn.\""},
];